# 生产环境配置

# 配置mysql数据源
spring:
  datasource:
    # 用户名
    username: root
    # 密码
    password: 123456
    # mysql的连接路径
    url: jdbc:mysql://116.62.54.239:3306/sport?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    # 配置驱动类
    driver-class-name: com.mysql.jdbc.Driver
  # redis相关配置
  redis:
    # 配置主机
    host: 116.62.54.239
    # 配置使用的数据库
    database: 0
    # 指定端口
    port: 6379
  # 邮件配置
  mail:
    # smtp服务主机(163) QQ：smtp.qq.com
    host: smtp.qq.com
    # 服务协议
    protocol: smtp
    # 设置编码集
    default-encoding: UTF-8
    # 允许测试连接
    test-connection: true
    # 设置发件人
    username: 1737194722@qq.com
    # 授权码  WXAMDNQSECKZDDAJ
    password: bxazkjooluvjebif