# 配置端口信息
server:
  port: 8000

# 配置项目名称
spring:
  author: 阿杰
  application:
    name: sport
  # 使用本地配置
  profiles:
    active: dev


# 配置mybatis
mybatis:
  # mapper接口找的xml文件
  mapper-locations: classpath:mapper/*.xml
  # 扫描的实体类
  type-aliases-package: com.ajie.entity
  # mybaits内置的配置
  configuration:
    # sql日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true


# redis相关配置


# jwt配置
jwt:
  # 请求头
  tokenHeader: Authorization
  # 签名加盐
  secret: ajiehencai123
  # jwt过期时间
  expiration: 1800000
  # token头部
  tokenHead: 'Bearer '

# 配置七牛云
qiniu:
  accessKey: KQB7m45iUcKAzZT4Z1mPfT6Fi5ErcPbZFPSDWPal
  secretKey: 0mm2CJs3h-i6ZvNZEpxx9ZBewYrNvHIzw5X5k514
  bucket: ajie-sport


# 配置阿里云短信服务
aliyun:
  # ak
  accessKey: LTAI4Fy3GWhBHPxmVKmYuBp4
  # sk
  secretKey: IFzcmKjZCaNhe8xbljYvQy7WQFo8uY
  # 签名
  signName: 阿杰通讯
  # 短信模板
  templateCode: SMS_208965510